
#include "tmv/TMV_Base.h"

template <class T> void TestAllSmallVector();
template <class T> void TestSmallVectorArith_1a();
template <class T> void TestSmallVectorArith_1b();
template <class T> void TestSmallVectorArith_2a();
template <class T> void TestSmallVectorArith_2b();
template <class T> void TestSmallVectorArith_2c();
template <class T> void TestSmallVectorArith_2d();
template <class T> void TestAllSmallMatrix();
template <class T> void TestSmallMatrix_Sub();
template <class T> void TestAllSmallMatrixA();
template <class T> void TestAllSmallMatrixB();
template <class T> void TestSmallMatrixArith_1();
template <class T> void TestSmallMatrixArith_2();
template <class T> void TestSmallMatrixArith_3();
template <class T> void TestSmallMatrixArith_4();
template <class T> void TestSmallMatrixArith_5();
template <class T> void TestSmallMatrixArith_6();
template <class T> void TestSmallMatrixArith_7();
template <class T> void TestAllSmallSquareDiv();
template <class T> void TestSmallSquareDiv_a();
template <class T> void TestSmallSquareDiv_b();
template <class T> void TestSmallSquareDiv_c();
template <class T> void TestSmallSquareDiv_a();
template <class T> void TestSmallSquareDiv_d();
template <class T> void TestSmallSquareDiv_e();
template <class T> void TestSmallSquareDiv_f();
template <class T> void TestSmallSquareDiv_g();
template <class T> void TestSmallMatrixDet();
template <class T> void TestAllSmallNonSquareDiv();
template <class T> void TestSmallNonSquareDiv_a();
template <class T> void TestSmallNonSquareDiv_b();
template <class T> void TestSmallNonSquareDiv_c();
template <class T> void TestSmallNonSquareDiv_d();
template <class T> void TestSmallNonSquareDiv_e();
template <class T> void TestSmallNonSquareDiv_f();
template <class T> void TestSmallNonSquareDiv_g();
