# vim: set filetype=python :

import os
Import('env')

libs=['tmv'] 

installed_linkfile = File('share/tmv-link',env['INSTALL_PREFIX']).abspath
#print "prefix = ",env['INSTALL_PREFIX']
#print "installed_linkfile =" , installed_linkfile

linkfile = File('#share/tmv-link').abspath
#print "linkfile =" , linkfile

cmd = 'rm -f $LINKFILE; '
cmd += 'echo $_LIBDIRFLAGS $_LIBFLAGS $LINKFLAGS > $LINKFILE; '
cmd += 'share/tmv-link-msg $LINKFILE $INSTALLED_LINKFILE'

#print "cmd = " , cmd

env1 = env.Clone(LIBS=libs+env['LIBS'],
    LINKFILE=linkfile, INSTALLED_LINKFILE=installed_linkfile,
    LIBPATH=env['LIBPATH2'])

if env['PREFIX'] != '':
    env1.AppendUnique(LIBPATH=os.path.join(env['INSTALL_PREFIX'], 'lib'))

#print "LIBPATH= " , env['LIBPATH']
#print "LIBPATH1= " , env1['LIBPATH']
#print "INSTALL_PREFIX= " , env['INSTALL_PREFIX']

env1.Command('#share/tmv-link','#share/tmv-link-msg',cmd)

env.Depends('#share/tmv-link', '#lib/libtmv.a')
env.Depends('#share/tmv-link', '#lib/libtmv_symband.a')

RunInstall = env['_InstallProgram']
RunUninstall = env['_UninstallProgram']

for fname in ['tmv-link']:

    cfile=env.File(fname)
    install_subdir = 'share'
    targets = [cfile]

    if 'install' in COMMAND_LINE_TARGETS:
        RunInstall(env, targets, install_subdir)

    if 'uninstall' in COMMAND_LINE_TARGETS:
        RunUninstall(env, targets, install_subdir)


