all:
	latex TMV_Documentation.tex
	latex TMV_Documentation.tex
	latex TMV_Documentation.tex
	makeindex TMV_Documentation.idx
	latex TMV_Documentation.tex
	latex TMV_Documentation.tex
	latex TMV_Documentation.tex
	dvipdf TMV_Documentation.dvi


